[package]
name = "ethereum"
version = "0.1.0"
authors = ["RJ Catalano <catalanor0220@gmail.com>", "Anthony Eufimio <Anthony's email here>"]
[dependencies]
hyper = "0.7.2"
tiny-keccak = "1.0.5"
bitcoin = "0.5.2"
rust-gmp = "0.2.10"
libc = "0.2.4"
